### ISSUE TITLE
Notification when toggling

### ISSUE THREAD

**Issue by jn64** [HuJohner/skin-toggle-mod#1]
Sometimes it's not obvious if you've toggled a part on or off, especially if you're in first-person view. So it would be nice to have a (optional) notification in chat or somewhere else, like "[Skin Toggle] Jacket off."

**Comment by HuJohner** [comment]
This is a good idea. In the next version, you will be able to activate 'announce toggles'.

Currently, I am using coloured text in the action bar to avoid cluttering the chat. What do you think?
![2021-01-27_23 09 17](https://user-images.githubusercontent.com/5261715/106060991-1295e700-60f5-11eb-9651-dc86fce62f31.png)
![2021-01-27_23 10 39](https://user-images.githubusercontent.com/5261715/106060992-132e7d80-60f5-11eb-8c81-37d5d5d0f26e.png)

**Comment by jn64** [comment]
I also thought of a graphical way (excuse the 5-second paint job)
![person](https://user-images.githubusercontent.com/23169302/106097778-de610b80-6172-11eb-9a53-acc290677772.png)

Just an idea. The text is good too.

**Comment by HuJohner** [comment]
I like that! This could be an additional option 'Skin Toggle Indicator'. Where would you expect this to be? In one of the corners, or next to the Hotbar?

**Comment by jn64** [comment]
I think top-left corner would be fine, similar to the paper doll on Bedrock.

**Comment by Julienraptor01** [comment]
i think the action bar message is really cool however due to server overusing it maybe just writing the text below so that it doesn't conflict with servers and datapack would be nice

**Comment by HuJohner** [comment]
Latest version adds the announce toggles option to the skin customisation menu. You can toggle between None (no announcement), chat, action bar (current and default)

**Comment by HuJohner** [comment]
And now I added the HUD suggestion as well. You can turn it off / change the position in the skin customisation menu
